"""
Parsing and evaluation utilities for LLM-generated NER outputs.

The LLM is asked to produce JSON such as:
    [{"entity": "Barack Obama", "type": "person"}, ...]

This module handles robust parsing with multiple fallback strategies and
converts entity lists back to BIO tag sequences for seqeval evaluation.
"""

from __future__ import annotations

import json
import re
from typing import Dict, List, Tuple

from rich.console import Console

console = Console()

VALID_TYPES = frozenset(
    ["person", "location", "corporation", "creative-work", "group", "product"]
)


# ---------------------------------------------------------------------------
# Parse LLM output
# ---------------------------------------------------------------------------


def parse_llm_output(output_text: str) -> Tuple[List[Dict[str, str]], str]:
    """Robustly parse JSON entity list from LLM output.

    Tries three strategies in order:
    1. Direct ``json.loads`` of the stripped text.
    2. Strip Markdown code fences (``` json ... ```) and parse.
    3. Regex search for a JSON array pattern ``[...]`` in the text.

    Parameters
    ----------
    output_text:
        Raw text generated by the LLM.

    Returns
    -------
    Tuple[List[Dict[str, str]], str]
        ``(entities, parse_status)``

        * ``entities``: Parsed list of entity dicts (may be empty on failure).
        * ``parse_status``: One of ``"ok"``, ``"markdown_stripped"``,
          ``"regex_fallback"``, ``"failed"``.
    """
    text = output_text.strip()

    # Filter <think>...</think> blocks from Qwen3 reasoning mode
    text = re.sub(r"<think>.*?</think>", "", text, flags=re.DOTALL).strip()

    # Strategy 1: direct parse
    try:
        result = json.loads(text)
        if isinstance(result, list):
            return _validate_entities(result), "ok"
    except json.JSONDecodeError:
        pass

    # Strategy 2: strip markdown fences
    fence_match = re.search(r"```(?:json)?\s*(.*?)\s*```", text, re.DOTALL)
    if fence_match:
        inner = fence_match.group(1).strip()
        try:
            result = json.loads(inner)
            if isinstance(result, list):
                return _validate_entities(result), "markdown_stripped"
        except json.JSONDecodeError:
            pass

    # Strategy 3: regex search for first [...] block
    array_match = re.search(r"\[.*?\]", text, re.DOTALL)
    if array_match:
        try:
            result = json.loads(array_match.group(0))
            if isinstance(result, list):
                return _validate_entities(result), "regex_fallback"
        except json.JSONDecodeError:
            pass

    return [], "failed"


def _validate_entities(raw: List) -> List[Dict[str, str]]:
    """Filter entity list to only include well-formed dicts with known types.

    Parameters
    ----------
    raw:
        Parsed JSON list (may contain dicts or garbage).

    Returns
    -------
    List[Dict[str, str]]
        Cleaned list with only valid entity dicts.
    """
    valid: List[Dict[str, str]] = []
    for item in raw:
        if not isinstance(item, dict):
            continue
        entity = item.get("entity", "")
        etype = item.get("type", "")
        if not isinstance(entity, str) or not entity.strip():
            continue
        if not isinstance(etype, str) or etype.strip().lower() not in VALID_TYPES:
            continue
        valid.append({"entity": entity.strip(), "type": etype.strip().lower()})
    return valid


# ---------------------------------------------------------------------------
# Convert entity list → BIO tag sequence
# ---------------------------------------------------------------------------


def entities_to_bio(
    tokens: List[str],
    entities: List[Dict[str, str]],
) -> List[str]:
    """Convert entity dicts to a BIO tag sequence aligned to tokens.

    Uses simple string matching: reconstructs the sentence from tokens,
    searches for each entity surface string, and marks the corresponding
    token positions.

    Parameters
    ----------
    tokens:
        Word tokens of the sentence.
    entities:
        List of ``{"entity": ..., "type": ...}`` dicts from LLM output.

    Returns
    -------
    List[str]
        BIO tag sequence of the same length as ``tokens``, e.g.
        ``["O", "B-person", "I-person", "O"]``.
    """
    bio_tags = ["O"] * len(tokens)

    for ent in entities:
        ent_text = ent["entity"]
        etype = ent["type"]

        # Tokenise the entity text the same way (split on whitespace)
        ent_tokens = ent_text.split()
        n = len(ent_tokens)

        # Slide over tokens to find first matching span
        for start in range(len(tokens) - n + 1):
            window = tokens[start : start + n]
            if window == ent_tokens:
                # Ensure no overlap with already-tagged spans
                if all(bio_tags[start + j] == "O" for j in range(n)):
                    bio_tags[start] = f"B-{etype}"
                    for j in range(1, n):
                        bio_tags[start + j] = f"I-{etype}"
                break  # Use first match only

    return bio_tags


# ---------------------------------------------------------------------------
# Evaluation wrapper
# ---------------------------------------------------------------------------


def evaluate_llm_predictions(
    tokens_list: List[List[str]],
    gold_entities: List[List[Dict[str, str]]],
    pred_entities: List[List[Dict[str, str]]],
    parse_statuses: List[str],
) -> Dict[str, float]:
    """Evaluate LLM NER predictions against gold entities using seqeval.

    Converts both gold and predicted entity lists to BIO sequences and
    computes entity-level F1.

    Parameters
    ----------
    tokens_list:
        List of token lists (one per sentence).
    gold_entities:
        Gold entity dicts per sentence.
    pred_entities:
        Predicted entity dicts per sentence.
    parse_statuses:
        Parse outcome per sentence (for computing parse failure rate).

    Returns
    -------
    Dict[str, float]
        Keys: precision, recall, f1, parse_failure_rate.
    """
    from seqeval.metrics import f1_score, precision_score, recall_score

    true_bio: List[List[str]] = []
    pred_bio: List[List[str]] = []

    for tokens, gold, pred in zip(tokens_list, gold_entities, pred_entities):
        true_bio.append(entities_to_bio(tokens, gold))
        pred_bio.append(entities_to_bio(tokens, pred))

    parse_fail_rate = parse_statuses.count("failed") / max(len(parse_statuses), 1)

    return {
        "precision": float(precision_score(true_bio, pred_bio, zero_division=0)),
        "recall": float(recall_score(true_bio, pred_bio, zero_division=0)),
        "f1": float(f1_score(true_bio, pred_bio, zero_division=0)),
        "parse_failure_rate": parse_fail_rate,
        "parse_ok": parse_statuses.count("ok"),
        "parse_markdown_stripped": parse_statuses.count("markdown_stripped"),
        "parse_regex_fallback": parse_statuses.count("regex_fallback"),
        "parse_failed": parse_statuses.count("failed"),
    }
